# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # To upgrade hooks run: `prek autoupdate`
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=750']
        exclude: ^uv.lock$
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: format
        name: check and reformat by ruff/ty/bandit
        entry: pdm run fast lint --ty --bandit
        language: system
        types: [python]

      - id: pypi
        name: ensure pypi for uv lock
        files: './^uv.lock'
        entry: pdm run fast pypi
        language: system
