[tool.poetry]
name = "fast-dev-cli"
version = "0.7.0"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]
readme = "README.md"
packages = [{include = "fast_dev_cli"}]

[tool.poetry.dependencies]
python = "^3.11"
click = ">=7.1.1"
ruff = {version = ">=0.3", optional = true}
mypy = {version = ">=1.5.0", optional = true}
coverage = {version = ">=6.5.0", optional = true}
bumpversion = {version = "^0.6.0", optional = true}
pytest = {version = "^8.1.1", optional = true}
typer = {version = ">=0.12.0", optional = true}

[tool.poetry.extras]
all = ["ruff", "typer", "mypy", "bumpversion", "pytest", "coverage"]

[tool.poetry.group.dev.dependencies]
ruff = ">=0.3"
mypy = "*"
pytest = "*"
coverage = "*"
bumpversion = "*"
typer = {extras = ["all"], version = "*"}
ipython = "^8.23.0"
coveralls = "^3.3.1"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
fast = "fast_dev_cli:cli"

[tool.ruff]
target-version = "py311"

[tool.mypy]
pretty = true
ignore_missing_imports = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.*"]
check_untyped_defs = false

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["E501"]
